MA-20707 Camera2Basic.apk exit after taking picture
Failed due to no GeneratedAppGlideModule in kotlin.
As workaround, don't display photo.
Will revert it after fix the issue.

09-25 03:58:25.293  2960  2960 W Glide   : Failed to find GeneratedAppGlideModule. You should include an annotationProcessor compile dependency
on com.github.bumptech.glide:compiler in your application and a @GlideModule annotated AppGlideModule implementation or LibraryGlideModules will be silently ignored

09-25 03:58:25.305  2960  2960 D AndroidRuntime: Shutting down VM

--------- beginning of crash
09-25 03:58:25.306  2960  2960 E AndroidRuntime: FATAL EXCEPTION: main
09-25 03:58:25.306  2960  2960 E AndroidRuntime: Process: com.example.android.camera2.basic, PID: 2960
09-25 03:58:25.306  2960  2960 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/bumptech/glide/gifdecoder/GifDecoder$BitmapProvider;
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.<init>(Glide.java:409)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.GlideBuilder.build(GlideBuilder.java:563)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.initializeGlide(Glide.java:314)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.initializeGlide(Glide.java:266)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:210)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.get(Glide.java:191)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.getRetriever(Glide.java:774)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.bumptech.glide.Glide.with(Glide.java:885)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.example.android.camera2.basic.fragments.ImageViewerFragment$onCreateView$1$2.invoke(ImageViewerFragment.kt:83)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.example.android.camera2.basic.fragments.ImageViewerFragment$onCreateView$1$2.invoke(ImageViewerFragment.kt:79)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.example.android.camera.utils.GenericListAdapter.onBindViewHolder(GenericListAdapter.kt:51)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at com.example.android.camera.utils.GenericListAdapter.onBindViewHolder(GenericListAdapter.kt:28)
09-25 03:58:25.306  2960  2960 E AndroidRuntime: 	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7395)

Change-Id: I2f67388dcc8e79cab365af86626fc30915638506
Signed-off-by: Fang Hui <hui.fang@nxp.com>
Reviewed-on: http://androidsource.ap.freescale.net/project/20013
Reviewed-by: Xuegang Liu <xuegang.liu@nxp.com>